### ISSUE TITLE
is there any way to verify email address?

### ISSUE THREAD

**Issue by kalpitpandit** [paypal/adaptiveaccounts-sdk-php#14]
i am searching around and i see there are mostly people are struggling to verify random email address with the paypal email addresses.

is there any way to verify given email address is registered with paypal?

**Comment by pp-randy** [comment]
I wanted to follow up and close this issue out, I apologize it has not been handled until now. 

You can use the GetVerifiedStatus API, but it would also require the name of the account holder. 
https://developer.paypal.com/docs/classic/api/adaptive-accounts/GetVerifiedStatus_API_Operation/
