### ISSUE TITLE
Class 'PayPal\Core\PPMessage' not found

### ISSUE THREAD

**Issue by trbsi** [paypal/adaptiveaccounts-sdk-php#16]
I installed PayPal Core and AdaptiveAccounts just for checking if user is verified, currently in sandbox mode. But I'm getting this message when I try to get verified status:
![screenhunter_67 sep 26 16 26](https://cloud.githubusercontent.com/assets/3958715/10117993/515da900-646b-11e5-9b28-05b59dc17daf.jpg)

**Comment by pp-randy** [comment]
I apologize for the delay in the following up on this issue.  

Are you still experiencing a problem with the most recent releases of both libraries?  

PPMessage should be in the core package https://github.com/paypal/sdk-core-php/blob/namespace-5.3/lib/PayPal/Core/PPMessage.php

**Comment by trbsi** [comment]
I don't even remember, I think I did by choosing different version of this sdk

**Comment by pp-randy** [comment]
Thank you for the response. Closing since this appears it isn't an issue for you currently.  

Again I apologize that your issue was not followed up on sooner.
