### ISSUE TITLE
No constructor in RequestEnvelope.php

### ISSUE THREAD

**Issue by vegazrelli** [paypal/adaptiveaccounts-sdk-php#17]
There is no constructor method in RequestEnvelope.php, so every object created with this class has errorLanguage null (I'm using also AdaptivePayments SDK, that has RequestEnvelope.php with constructor.

**Comment by pp-randy** [comment]
Is adding the constructor something you would consider submitting a pull request for?

**Comment by vegazrelli** [comment]
YES!

Nicola Riparelli
Mail vegazrelli@gmail.com
Mobile +39 340 38 00 706


2016-04-22 15:55 GMT+02:00 Randy <notifications@github.com>:

**Comment by DavidWard1980** [comment]
submitting method when i am done with script

**Comment by tmukherjee13** [comment]
I have submitted created a pull request for this bug.

**Comment by pp-randy** [comment]
Sorry for the delay, I have reached out to the SDK engineers to review the pull request.
