### ISSUE TITLE
Can matchCriteria NONE in GetVerifiedStatus API call ?

### ISSUE THREAD

**Issue by dmahesh22** [paypal/adaptiveaccounts-sdk-php#19]
As per [Paypal Doc's](https://developer.paypal.com/webapps/developer/docs/classic/api/adaptive-accounts/GetVerifiedStatus_API_Operation/) `matchCriteria` can be `NONE` only for for certain financial institutions, what does it mean ? With sending `firstName` & `lastName` empty values and `matchCriteria` as `NONE` in sandbox environment I'm getting expected response from API call, will this also work in live environment ?

**Comment by pp-randy** [comment]
Unless you are exempt from the requirement like the documentation describes you would need FirstName and LastName on live.  

I apologize for the delay, please let me know if you have further questions.
